name: P2_circ_disruption_environment 

dependencies:
- python = 3.7
- numpy == 1.15
- pandas == 0.23.3
- matplotlib == 2.2.3
- ipykernel == 5.1.0
- pip
- pip:
  - git+https://github.com/A-Fisk/actigraphy_analysis.git@master
 

